# NTP 4.2.8p15 as illumos-extra builds it for the platform (ntp/Makefile): 32 bits, its six patches applied with -p0
# (PATCHSTRIP), configure regenerated by `autoreconf -fi` (UNPACK_SENTINEL is configure.ac), CFLAGS for CTF, crypto
# through the platform's OpenSSL names (--with-crypto=sunw), the scripts pointed at the platform's perl
# (/usr/perl5/bin/perl, /usr/perl5/5.12/lib); installed by `make install`, then CTF for its programs by tools/make-ctf,
# then ntp/install-ntp (configuration, SMF manifest and method, RBAC fragments, manuals). The manuals go to
# --mandir=/usr/man, which their proto area has as a link to share/man; the link is made for the install and removed
# after it.
#
# illumos-extra bug, reproduced: configure's environment gets LD_OPTIONS="$(LDFLAGS)", the compiler driver's flags
# (-L..., -Wl,...) handed to the link-editor itself through its environment.
#
# The top Makefile makes it wait for perl and openssl3; ntp links OpenSSL (libsunw_crypto) and installs NTP/Util.pm
# into the platform perl's library, whose path it is given. autoreconf is nixpkgs' autoconf, automake and libtool
# (theirs: pkgsrc's).
{
  cleanEnv,
  mkAutoconf,
  autoconf,
  automake,
  libtool,
  ctfconvert,
  openssl3,
}:

let
  programs = [
    "ntp-keygen"
    "ntpd"
    "ntpdate"
    "ntpdc"
    "ntpq"
    "ntptime"
    "tickadj"
  ];
in
mkAutoconf {
  pname = "smartos-extra-ntp";
  version = "4.2.8p15";
  dir = "ntp";
  extraDirs = [ "tools" ];
  ver = "ntp-4.2.8p15";
  patches = "Patches/*";
  patchStrip = 0;
  deps = [ openssl3 ];
  nativeBuildInputs = [
    autoconf
    automake
    libtool
  ];
  frob = ''(cd $d && ${cleanEnv} PATH="$PATH" ACLOCAL_PATH="$ACLOCAL_PATH" autoreconf -fi)'';
  cflags = "-O2 -gdwarf-2 -fno-inline-functions -fno-inline-functions-called-once -fno-inline-small-functions";
  configureEnv = f: ''LD_OPTIONS="${f.ldflags}"'';
  configureFlags = [
    "--prefix=/usr"
    "--mandir=/usr/man"
    "--bindir=/usr/sbin"
    "--with-binsubdir=sbin"
    "--libexecdir=/usr/sbin"
    "--sysconfdir=/etc/inet"
    "--with-perl=/usr/perl5/bin/perl"
    "--with-perllibdir=/usr/perl5/5.12/lib"
    "--enable-all-clocks"
    "--enable-debugging"
    "--enable-debug-timing"
    "--disable-optional-args"
    "--enable-parse-clocks"
    "--enable-ignore-dns-errors"
    "--without-ntpsnmpd"
    "--without-lineeditlibs"
    "--with-crypto=sunw"
    "--without-sntp"
    "--enable-local-libevent"
    "--disable-getifaddrs"
  ];
  install = suffix: ''
    mkdir -p $out/usr/share/man
    ln -s share/man $out/usr/man
    (cd ntp-4.2.8p15-32${suffix} && ${cleanEnv} PATH="$PATH" make DESTDIR=$out install)
    ${cleanEnv} PATH="$PATH" DESTDIR=$out CTFCONVERT=${ctfconvert} CTFCONVERTFLAGS= \
      bash ../tools/make-ctf ntp-4.2.8p15-32${suffix} ctfobjects-32${suffix} ntp-4.2.8p15 \
      ${toString (map (p: "/usr/sbin/${p}") programs)}
    ${cleanEnv} PATH="$PATH" DESTDIR=$out bash -e ./install-ntp
    rm $out/usr/man
  '';
}
