# OpenSSH 10.5p1 as illumos-extra builds it for the platform (openssh/Makefile): 32 bits, its 33 patches (the SunSSH
# compatibility, PAM, audit, contracts and privileges work, DTrace probes for sftp, the SMF manifest and method),
# configure regenerated by `autoreconf -fi` (UNPACK_SENTINEL is configure.ac), Kerberos, PAM, BSM audit and TCP
# wrappers from the proto area, CFLAGS for CTF and the patches' feature macros, LDFLAGS -B direct -z nolazyload and
# ASLR; installed by `make install`, then CTF for its programs by tools/make-ctf.
#
# The patches run the platform's dtrace at build time (dtrace -G), as for illumos-extra. --with-xauth names pkgsrc's
# /opt/local/bin/xauth, a path ssh records, as theirs. The top Makefile makes it wait for openssl3; the platform's
# programs link OpenSSL and zlib, so both are given. autoreconf is nixpkgs' autoconf and automake (theirs: pkgsrc's).
{
  mkAutoconf,
  autoconf,
  automake,
  platformDtrace,
  ctfconvert,
  illumosProto,
  hostTools,
  libz,
  openssl3,
}:

let
  programs = [
    "/usr/bin/ssh"
    "/usr/bin/scp"
    "/usr/bin/ssh-add"
    "/usr/bin/ssh-agent"
    "/usr/bin/ssh-keygen"
    "/usr/bin/ssh-keyscan"
    "/usr/bin/sftp"
    "/usr/lib/ssh/sshd"
    "/usr/lib/ssh/ssh-keysign"
    "/usr/lib/ssh/ssh-pkcs11-helper"
    "/usr/lib/ssh/sftp-server"
  ];
in
mkAutoconf {
  pname = "smartos-extra-openssh";
  version = "10.5p1";
  dir = "openssh";
  extraDirs = [ "tools" ];
  ver = "openssh-10.5p1";
  patches = "Patches/*";
  deps = [
    libz
    openssl3
  ];
  # hostTools: configure picks the manuals' format by the formatter it finds (their build host: /usr/bin/mandoc)
  nativeBuildInputs = [
    autoconf
    automake
    platformDtrace
    hostTools
  ];
  frob = ''(cd $d && env -i PATH="$PATH" ACLOCAL_PATH="$ACLOCAL_PATH" autoreconf -fi)'';
  cflags = toString [
    "-O2 -gdwarf-2 -fno-inline-functions -fno-inline-functions-called-once -fno-inline-small-functions"
    "-DSET_USE_PAM -DDEPRECATE_SUNSSH_OPT -DKRB5_BUILD_FIX -DDTRACE_SFTP -DDISABLE_BANNER -DPAM_ENHANCEMENT"
    "-DPAM_BUGFIX -DOPTION_DEFAULT_VALUE -DHAVE_EVP_SHA256 -DPER_SESSION_XAUTHFILE"
    "-I${illumosProto}/usr/include/kerberosv5"
  ];
  ldflags = "-B direct -z nolazyload -Wl,-zaslr";
  configureFlags = [
    "--libexecdir=/usr/lib/ssh"
    "--sbindir=/usr/lib/ssh"
    "--sysconfdir=/etc/ssh"
    "--bindir=/usr/bin"
    "--with-audit=solaris"
    "--with-kerberos5=${illumosProto}/usr"
    "--with-pam"
    "--with-sandbox=solaris"
    "--with-solaris-contracts"
    "--with-solaris-privs"
    "--with-tcp-wrappers"
    "--with-4in6"
    "--with-Werror=no"
    "--enable-strip=no"
    "--without-rpath"
    "--disable-lastlog"
    "--with-privsep-user=daemon"
    "--without-openssl-header-check"
    "--with-key-dir=/var/ssh"
    "--with-sys-moduli=/usr/share/lib/ssh/moduli"
    "--with-xauth=/opt/local/bin/xauth"
  ];
  install = suffix: ''
    (cd openssh-10.5p1-32${suffix} && env -i PATH="$PATH" make V=1 install DESTDIR=$out)
    rm openssh-10.5p1-32${suffix}/sftp_provider.o
    env -i PATH="$PATH" DESTDIR=$out CTFCONVERT=${ctfconvert} CTFCONVERTFLAGS= \
      bash ../tools/make-ctf openssh-10.5p1-32${suffix} ctfobjects-32${suffix} openssh-10.5p1 ${toString programs}
  '';
}
