# GNU wget 1.25.0 as illumos-extra builds it for the platform (wget/Makefile): 32 bits, its three patches (OpenSSL's
# platform names among them), configure regenerated by `autoreconf` with the package's pkg.m4 (UNPACK_SENTINEL is
# configure.ac), configure given LD_OPTIONS naming mapfile_noexstk (configure only), PERL and POD2MAN, CFLAGS for
# CTF (-gdwarf-2, no inlining); installed as their install target does: the program and its manual, then CTF from the
# program's DWARF by tools/make-ctf (ctfconvert from the illumos build's tools stage, then strip -x).
#
# Their PERL and POD2MAN are pkgsrc's (/opt/local/bin); here nixpkgs' perl and its pod2man, which make the manual
# (texi2pod.pl also runs as `/usr/bin/env perl`, from PATH, where the scope puts perl); so wget.1 is Pod::Man
# 6's, theirs 5's. Their autoreconf is pkgsrc's autoconf, automake and gettext, here nixpkgs'. The top Makefile makes
# it wait for openssl3 and libidn; the platform's wget links OpenSSL and zlib (no IDN: wget 1.25 looks for libidn2
# through pkg-config, and PKG_CONFIG_LIBDIR is empty), so those two are given.
{
  cleanEnv,
  mkAutoconf,
  perl,
  autoconf,
  automake,
  gettext,
  flex,
  ctfconvert,
  libz,
  openssl3,
}:

mkAutoconf {
  pname = "smartos-extra-wget";
  version = "1.25.0";
  dir = "wget";
  extraDirs = [ "tools" ];
  ver = "wget-1.25.0";
  patches = "Patches/*";
  deps = [
    libz
    openssl3
  ];
  nativeBuildInputs = [
    autoconf
    automake
    gettext
    flex
  ];
  frob = ''
    test -f $d/m4/pkg.m4 || cp pkg.m4 $d/m4/pkg.m4
    (cd $d && ${cleanEnv} PATH="$PATH" ACLOCAL_PATH="$ACLOCAL_PATH" autoreconf)
  '';
  cflags = "-O2 -gdwarf-2 -fno-inline-functions -fno-inline-functions-called-once -fno-inline-small-functions";
  # $(BASE)/mapfile_noexstk: the illumos-extra directory, one above the build directory
  configureEnv = ''LD_OPTIONS="-M $PWD/../mapfile_noexstk" PERL=${perl}/bin/perl POD2MAN=${perl}/bin/pod2man'';
  configureFlags = [
    "--sysconfdir=/etc"
    "--with-ssl=openssl"
    "--infodir=/usr/share/info"
    "--disable-rpath"
  ];
  install = suffix: ''
    mkdir -p $out/usr/bin $out/usr/share/man/man1
    install -m 0555 wget-1.25.0-32${suffix}/src/wget $out/usr/bin/wget
    install -m 0444 wget-1.25.0-32${suffix}/doc/wget.1 $out/usr/share/man/man1
    ${cleanEnv} PATH="$PATH" DESTDIR=$out CTFCONVERT=${ctfconvert} CTFCONVERTFLAGS= \
      bash ../tools/make-ctf wget-1.25.0-32${suffix} ctfobjects-32${suffix} wget-1.25.0 /usr/bin/wget
  '';
}
